name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

env:
  CARGO_TERM_COLOR: always

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request_target' ||
      github.event.pull_request.author_association == 'COLLABORATOR' ||
      contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
  
    - name: Build agent binary
      run: cargo build
    
    - name: Run integration tests
      run: |
        cd integration-tests
        cargo test -- --test-threads=1
